fail_fast: true

repos:

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff-format
        args: [integration, reflex, tests]
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        exclude: '^integration/benchmarks/'

  - repo: local
    hooks:
      - id: poetry_check
        name: poetry_check
        language: system
        entry: poetry check
        pass_filenames: false
      - id: poetry_install
        name: poetry_install
        language: system
        entry: poetry install
        pass_filenames: false
      - id: pyright
        name: pyright
        language: system
        entry: poetry run pyright integration reflex tests
        pass_filenames: false
      - id: darglint
        name: darglint
        language: system
        entry: poetry run darglint
        exclude: '^reflex/reflex.py'
      - id: update-pyi-files
        name: update-pyi-files
        language: system
        entry: python scripts/make_pyi.py
        always_run: true
        description: 'Update pyi files as needed'
