version: '3.8'

services:
  app:
    build:
      context: ./docker-example
      dockerfile: prod.Dockerfile
      args:
        - BUILD_ID=${BUILD_ID:-default_build_id}
    volumes:
      - db-data:/app/data
      - upload-data:/app/uploaded_files
    restart: always
    environment:
      DB_URL: postgres://username:password@db:5432/reflex

  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: reflex
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    restart: always

  redis:
    image: redis:alpine
    restart: always

  webserver:
    environment:
      DOMAIN: ${DOMAIN:-localhost}
    ports:
      - 8444:443  # Zmiana portu na 8444
      - 8081:80   # Zmiana portu na 8081
    build:
      context: ./docker-example
      dockerfile: Caddy.Dockerfile
      args:
        - BUILD_ID=${BUILD_ID:-default_build_id}
    volumes:
      - caddy-data:/root/.caddy
    restart: always
    depends_on:
      - app

volumes:
  db-data:
  upload-data:
  caddy-data:
