name: codspeed-benchmarks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: ./.github/actions/setup_build_env
        with:
          # running vs. one version of Python is OK
          # i.e. ruff, black, etc.
          python-version: 3.11.5
          run-poetry-install: true
          shell: bash
          create-venv-at-path: .venv

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v1
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: poetry run pytest tests/ --codspeed