name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup_build_env
      with:
          python-version: ${{ matrix.python-version }}
          run-poetry-install: true
          shell: bash
          create-venv-at-path: .venv
    - run: poetry run pytest tests --cov --no-cov-on-fail --cov-report=
    - run: poetry run pyright reflex tests
    - run: poetry run ruff check . --format github
    - run: find reflex tests -name "*.py" -not -path reflex/reflex.py | xargs poetry run darglint
    - run: poetry run black --check reflex tests
    - run: poetry run coverage html
