name: integration-test-examples

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    # Specify python/node versions to test against
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        node-version: ["16.x"]
      
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    # Clone Reflex Website Repo For integration tests
    - name: Clone Reflex Examples Repo
      uses: actions/checkout@v3
      with:
        repository: pynecone-io/pynecone-examples
        path: pynecone-examples

    - name: cache poetry install
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: python-${{ matrix.python-version }}-poetry-1.3.1

    - uses: snok/install-poetry@v1
      with:
        version: 1.3.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: cache deps
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: .venv
        key: python-${{ matrix.python-version }}-pydeps-${{ hashFiles('**/poetry.lock') }}

    - name: install nvm
      run:  |
        ls -a $HOME
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
        cat ~/.bashrc
        source ~/.bashrc
        nvm install v16.2.0
        echo "========================================="
    - name: Poetry Install
      run: poetry install --no-interaction
    - name: Install Requirements
      working-directory: ./pynecone-examples/counter
      run: poetry run pip install -r requirements.txt
    - name: Init Website
      working-directory: ./pynecone-examples/counter
      run: |
        poetry run reflex init
        cat ~/.bashrc
        echo "========================================="
    - name: Validate Reflex's own installation of Node
      run: |
        /home/runner/.reflex/.nvm/versions/node/v*/bin/npm -v
        /home/runner/.reflex/.nvm/versions/node/v*/bin/node -v
    - name: Check for errors
      run: |
        chmod +x ./scripts/integration.sh
        ./scripts/integration.sh ./pynecone-examples/counter dev
