name: integration-test-website

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    # Specify python/node versions to test against
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        node-version: ["16.x"]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version }}

    - uses: ./.github/actions/setup_build_env
      with:
        python-version: ${{ matrix.python-version }}
        run-poetry-install: true
        shell: bash
        create-venv-at-path: .venv

      # Clone Reflex Website Repo For integration tests
    - name: Clone Reflex Website Repo
      uses: actions/checkout@v3
      with:
        repository: pynecone-io/pcweb
        path: pcweb

    - name: Install Requirements for reflex-web
      working-directory: ./pcweb
      run: poetry run pip install -r requirements.txt
    - name: Init Website for reflex-web
      working-directory: ./pcweb
      run: poetry run reflex init
    - name: Run Website and Check for errors
      run: |
        chmod +x ./scripts/integration.sh
        ./scripts/integration.sh ./pcweb prod
